apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-application
  template:
    metadata:
      labels:
        app: banking-application
    spec:
      containers:
        - name: banking-application
          image: praveenhema/newupgrde:latest
          ports:
            - containerPort: 8080  # Your Node.js application should listen on port 3000

---

apiVersion: v1
kind: Service
metadata:
  name: banking-application-service
spec:
  selector:
    app: banking-application
  ports:
    - protocol: TCP
      port: 80  # You can use port 80 here for HTTP traffic
      targetPort: 8080  # This should match the port your Node.js application is running on (3000)
  type: LoadBalancer
